#!/bin/sh

alias \
		wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"' \
		gpg2='gpg2 --homedir "$XDG_DATA_HOME"/gnupg'

# git aliases
alias \
		gst='git status' \
		gcm='git commit' \
		gdf='git diff' \
		gad='git add'

alias \
		r='ranger' \
		imwheel='imwheel --kill -b 45' \
		update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
		nas-mount="sudo mount -t cifs -o username=Marco,uid=$(id -u),gid=$(id -g) //192.168.1.136/Plex /mnt"
