let mapleader =" "

" basics
syntax enable
filetype plugin on
colorscheme default
set nocompatible
set encoding=utf-8
set number relativenumber

" finding files in a fuzzy way
set path+=**
set wildmenu

" tabs
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smartindent
set nohlsearch
set incsearch

set scrolloff=10
set signcolumn="yes"
set colorcolumn=80

" NETRw config
let g:netrw_banner=0
let g:netrw_browse_split=4
let g:netrw_altv=1
let g:netrw_liststyle=3
let g:netrw_list_hide=netrw_gitignore#Hide()
let g:netrw_list_hide.=',\(^\|\s\s\)\zs\.\S\+'
nnoremap <leader>pv :Ex<CR>

" remaps
nnoremap n nzzzv
nnoremap N Nzzzv
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
nnoremap J mzJ`z
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv

" substitue all occurences of word under cursor
nnoremap <leader>s :%s/\<<C-r><C-w>\>/<C-r><C-w>/gI<Left><Left><Left>

" Save file as sudo on files that require root permission
cnoremap w!! execute 'silent! write !sudo tee % >/dev/null' <bar> edit!

" Automatically deletes all trailing whitespace on save
autocmd BufWritePre * %s/\s\+$//e
