#! /bin/sh

# Display settings
xrandr --output DVI-I-1 --mode 1920x1080 --rate 144.00
xrandr --output HDMI-0 --mode 1920x1080 --rate 60.00 --right-of DVI-I-1
displaycal-apply-profiles

# Set wallpaper
feh --bg-scale /media/immagini/wallpaper/wp.jpg --no-fehbg
picom --experimental-backends &

# Notification | Music | Mouse | Eyes | Cursor
dunst &
pidof mpd || mpd
imwheel --kill -b 45
pidof redshift || redshift -l 45:10 &> /dev/null &
pidof megasync || megasync &
xsetroot -cursor_name left_ptr

# polybar
$HOME/.config/polybar/launch.sh

# bspwm
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor DVI-I-1 -d I II III IV V
bspc monitor HDMI-0 -d VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp state=floating follow=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a MEGAsync state=floating rectangle=1x1+1470+50
bspc rule -a Steam state=floating
