#!/usr/bin/env sh

# Simple script that lunch a tmux session with splitted cmus and lyrpy

SESSION="cmus_lyrpy"

pkill cmus
tmux new-session -s $SESSION -d 'cmus'
tmux split-window -h -t $SESSION 'lyrpy'
tmux attach-session -t $SESSION

exit 0
