#!/usr/bin/env sh

# gtpu (Gcode To Prusa Usb)

# This is a simple script that copies the latest modified gcode file inside a
# folder and its subdirectory on the usb used by my PRUSA MINI 

USB_LABEL="PRUSA_MINI"
USB_PATH=$(lsblk -l -o PATH,LABEL | grep $USB_LABEL | cut -d" " -f1)
USB_MOUNTPOINT=$(lsblk -l -o MOUNTPOINT,LABEL | grep $USB_LABEL | cut -d" " -f1)

GCODE_DIR=/media/documenti/3d_printing
LAST_MODIFIED_GCODE=$(find $GCODE_DIR -type f \
                                      -name "*.bgcode" \
                                      -exec stat --format '%Y %n' "{}" \; \
                                      | sort -nr | cut -d " " -f2 | head -1)

# Check if the USB stick is plugged in
if [[ -z "$USB_PATH" ]]; then
    echo "ERROR: The USB stick isn't plugged in"
    exit 1
fi

# Let the user know what file is going to be copied
echo This script will copy \'${LAST_MODIFIED_GCODE##*/}\' to $USB_PATH 
read -p "Continue? (y/n) " confirm
if [[ "$confirm" != [yY] ]]; then
    echo Aborting...
    exit 0
fi

# If the drive isn't already mounted, mount it
if [[ -z "$USB_MOUNTPOINT" ]]; then
    udisksctl mount -b $USB_PATH && sleep 1
    USB_MOUNTPOINT=$(lsblk -l -o MOUNTPOINT,LABEL | grep $USB_LABEL | cut -d" " -f1)
fi

# Copy the file to the USB stick
cp -f $LAST_MODIFIED_GCODE $USB_MOUNTPOINT/ && sleep 1
echo "File copied successfully!"

# Unmount and poweroff the USB stick to safe eject
udisksctl unmount -b $USB_PATH && sleep 1

echo "The USB can be safely eject now, happy printing :)"

exit 0
