#!/usr/bin/env sh

# latexmk + tmux + zathura

# get the first tex file in current working directory
TEX_FILE="$(find -maxdepth 1 -name "*.tex" | head -n 1)"

zathura "${TEX_FILE:2:-4}.pdf" &> /dev/null &

tmux new-session -s "ltmx" -n "latexmk" -d "latexmk -pvc -pdf -shell-escape"
tmux new-window -n "zsh"
tmux new-window -n "nvim" -d "$EDITOR $TEX_FILE"
tmux -2 attach-session -d

latexmk -c

exit 0
