#!/usr/bin/env sh

# Print default sink device and volume

HEADPHONE="alsa_output.usb-Schiit_Audio_I_m_Fulla_Schiit-00.analog-stereo"
SPEAKER="alsa_output.pci-0000_28_00.4.analog-stereo"

# Get default sink
case "$(pactl get-default-sink)" in
	$HEADPHONE) SINK="H" ;;
	$SPEAKER) SINK="S" ;;
	*) SINK="?"
esac

# Get the volume of default sink
VOLUME="$(pactl get-sink-volume $(pactl get-default-sink) | head -n 1 | cut -d "/" -f2)"

echo $VOLUME $SINK

exit 0
