#!/bin/sh

alias \
		cls="clear" \
		nb="newsboat" \
		grep="grep --color" \
		sdn="killall -q Discord; shutdown -h 0" \
		rbt="killall -q Discord; shutdown -r 0" \
		ls="ls -lh --color=auto --group-directories-first" \
		wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"' \
		gpg2='gpg2 --homedir "$XDG_DATA_HOME"/gnupg'

# git aliases
alias \
		gst='git status' \
		gcm='git commit' \
		gdf='git diff' \
		gad='git add'

alias \
		imwheel='imwheel --kill -b 45' \
		backup="sudo ~/.local/bin/backup" \
		update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
		nas-mount="sudo mount -t cifs //nas-backup/admin /nas -o user=admin,vers=1.0" \
