#!/bin/sh

# Gotta type lezz
alias \
		cls="clear" \
		nm="neomutt" \
		nb="newsboat" \
		r="ranger" \
		pm="pulsemixer"\
		grep="grep --color" \
		sdn="killall -q Discord; shutdown -h 0" \
		reboot="killall -q Discord; shutdown -r 0" \
		ls="ls -lh --color=auto --group-directories-first" \
		wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"' \
		gpg2='gpg2 --homedir "$XDG_DATA_HOME"/gnupg' \
		mbsync='mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc' \
		mb='mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc gmail' \
		gst='git status'

alias \
		imwheel='imwheel --kill -b 45' \
		backup="sudo ~/.local/bin/backup" \
		update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
		nas-mount="sudo mount -t cifs //nas-backup/admin /nas -o user=admin,vers=1.0" \
		case_check='echo -n "Arrivo previsto Phankteks P400A: ";curl "http://www.drako.it/drako_catalog/product_info.php?products_id=23517" &> /dev/null | grep -A 4 'DISPONIBILITA' | tail -n 1 | cut -d">" -f3 | cut -d"<" -f1'
		

#alias drivep="CUR_DIR=$(pwd); cd ~/gdrive && drive push && cd $CUR_DIR"


