#!/usr/bin/env sh

# Folder shortcuts
alias b="cd ~/.local/bin"
alias C="cd ~/.config"
alias c="cd ~/documenti/code"
alias d="cd ~/documenti"
alias D="cd ~/Downloads"
alias i="cd ~/immagini"
alias l="cd ~/video/lezioni"
alias m="cd ~/musica"
alias o="cd ~/dotfiles"
alias p="cd ~/documenti/Progetti"
alias t="cd ~/documenti/Progetti/tex"
alias T="cd /media/torrents"
alias u="cd ~/documenti/università/unibo"
alias v="cd ~/video"
alias w="cd ~/documenti/Progetti/site/website"

# NNN Folder shortcuts
export NNN_BMS='b:~/.local/bin;C:~/.config;c:~/documenti/code;d:~/documenti;D:~/Downloads;i:~/immagini;l:~/video/lezioni;m:~/musica;o:~/dotfiles;p:~/documenti/Progetti;t:~/documenti/Progetti/tex;T:/media/torrents;u:~/documenti/università/unibo;v:~/video;w:~/documenti/Progetti/site/website;'

# Change config file shortcuts
alias cfa="$EDITOR ~/.config/shortcutrc/aliasrc"
alias cfb="$EDITOR ~/.config/bspwm/bspwmrc"
alias cfc="$EDITOR ~/.config/shortcutrc/configrc"
alias cff="$EDITOR ~/.config/shortcutrc/folderc"
alias cfp="$EDITOR ~/.config/polybar/config"
alias cfs="$EDITOR ~/.config/sxhkd/sxhkdrc"
alias cfu="$EDITOR ~/.config/newsboat/urls"
alias cfv="$EDITOR ~/.config/nvim/init.vim"
alias cfz="$EDITOR ~/.config/zsh/.zshrc"
