#!/usr/bin/env sh

# Folder shortcuts
alias b="cd ~/.local/bin"
alias C="cd ~/.config"
alias c="cd ~/documenti/code"
alias d="cd ~/documenti"
alias D="cd ~/Downloads"
alias h="cd ~/"
alias i="cd ~/immagini"
alias l="cd ~/video/lezioni"
alias m="cd ~/musica"
alias P="cd ~/documenti/code/python/lyrpy"
alias p="cd ~/documenti/Progetti"
alias t="cd ~/documenti/Progetti/tex"
alias T="cd /media/torrents"
alias u="cd ~/gdrive/Uni"
alias v="cd ~/video"
alias w="cd ~/documenti/Progetti/site/website"

# NNN Folder shortcuts
export NNN_BMS='b:~/.local/bin;C:~/.config;c:~/documenti/code;d:~/documenti;D:~/Downloads;h:~/;i:~/immagini;l:~/video/lezioni;m:~/musica;P:~/documenti/code/python/lyrpy;p:~/documenti/Progetti;t:~/documenti/Progetti/tex;T:/media/torrents;u:~/gdrive/Uni;v:~/video;w:~/documenti/Progetti/site/website;'

# Change config file shortcuts
alias cfD="$EDITOR ~/.local/bin/start_dwm"
alias cfF="$EDITOR ~/.config/shortcutrc/folderc"
alias cfa="$EDITOR ~/.config/shortcutrc/aliasrc"
alias cfb="$EDITOR ~/.bashrc"
alias cfc="$EDITOR ~/.config/shortcutrc/configrc"
alias cfd="$EDITOR ~/.Xdefaults"
alias cfr="$EDITOR ~/.config/ranger/rc.conf"
alias cfu="$EDITOR ~/.config/newsboat/urls"
alias cfv="$EDITOR ~/.config/nvim/init.vim"
alias cfz="$EDITOR ~/.config/zsh/.zshrc"
