#!/bin/sh

# Gotta type lezz
alias \
		cls="clear" \
		n="neomutt" \
		r="ranger" \
		pm="pulsemixer"\
		grep="grep --color" \
		sdn="shutdown -h 0" \
		reboot="shutdown -r 0" \
		ls="ls -lh --color=auto --group-directories-first" \
		wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"' \
		gpg2='gpg2 --homedir "$XDG_DATA_HOME"/gnupg' \
		mbsync='mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc'


alias \
		imwheel='imwheel --kill -b 45' \
		backup="sudo ~/.local/bin/backup" \
		update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
		nas-mount="sudo mount -t cifs //nas-backup/admin /nas -o user=admin,vers=1.0" \
		lol='sudo sh -c "sysctl -w abi.vsyscall32=0"'

#alias drivep="CUR_DIR=$(pwd); cd ~/gdrive && drive push && cd $CUR_DIR"


