#!/bin/sh

alias \
		wget='wget --hsts-file="$XDG_CACHE_HOME/wget-hsts"' \
		gpg2='gpg2 --homedir "$XDG_DATA_HOME"/gnupg'

# git aliases
alias \
		gst='git status' \
		gcm='git commit' \
		gdf='git diff' \
		gad='git add'

alias \
		imwheel='imwheel --kill -b 45' \
		update-grub="sudo grub-mkconfig -o /boot/grub/grub.cfg" \
		nas-mount="sudo mount -t cifs //nas-backup/admin /nas -o user=admin,vers=1.0"
